### ISSUE TITLE
Look <NPC> still broken

### ISSUE THREAD

**Issue by wizardsambolton** [MoreOutput/RockMUD#101]
(Sorry if you know this already!) Causing the server to stop responding

**Comment by MoreOutput** [comment]
look boar and etc seem to be working. the one issue i've found is related to looking at thomas; that mobs name value is incorrect (reading tom rather than thomas -- will be fixed).

 Considering also trying to match against long description when a look attempt fails.

**Comment by wizardsambolton** [comment]
Although with my own NPCs it dosnt seem to work either?
