### ISSUE TITLE
Look listing other players multiple times.

### ISSUE THREAD

**Issue by wizardsambolton** [MoreOutput/RockMUD#105]
![screen shot 2016-08-21 at 21 39 06](https://cloud.githubusercontent.com/assets/5786546/17842359/c52866f6-67e7-11e6-869d-448aacccdd6b.png)

**Comment by MoreOutput** [comment]
Not seen this; will check after work today.

**Comment by wizardsambolton** [comment]
Thanks!

**Comment by wizardsambolton** [comment]
Ok I have restarted the server and now that is not happening however, look is listing every player in every room.

**Comment by wizardsambolton** [comment]
@MoreOutput

**Comment by wizardsambolton** [comment]
Also it does still list the other players multiple times if you leave the area and then return to it.

**Comment by wizardsambolton** [comment]
Also it does still list the other players multiple times if you leave the area and then return to it.

**Comment by MoreOutput** [comment]
https://github.com/MoreOutput/RockMUD/issues/114
