### ISSUE TITLE
For some reason NPC messages (E.G Radghar) are broadcasting to every area+room

### ISSUE THREAD

**Issue by wizardsambolton** [MoreOutput/RockMUD#108]

**Comment by wizardsambolton** [comment]
Ok I have realised why this is happening its because the SAY command is broadcasting to every room.

**Comment by wizardsambolton** [comment]
Although it only works like that when mobs fire it.

**Comment by MoreOutput** [comment]
I cant replicate this -- may be fixed on my end. like the other issue im leaving it open. Say broadcasts to everyone in the room; for both of my chars to get the message they need to be in the room with radghar which is expected.

Im on gitter this evening.

**Comment by wizardsambolton** [comment]
![screen shot 2016-08-23 at 19 31 43](https://cloud.githubusercontent.com/assets/5786546/17914511/63ac1288-6968-11e6-9cb1-2cee54d21e5c.png)

As you can see the Greyhawk Info broker, is not currently standing in the current room and actually in a different area.

**Comment by MoreOutput** [comment]
see: https://github.com/MoreOutput/RockMUD/issues/114
