### ISSUE TITLE
Break out Rooms from Areas

### ISSUE THREAD

**Issue by fly-man-** [MoreOutput/RockMUD#47]
Please break the rooms out of the areas, when editing or adding to the Area code now, the server goes into a reboot, kicking all the users offline

Or add an ability to load the rooms dynamically so the server doesn't have to be rebooted

**Comment by MoreOutput** [comment]
This will be fixed in 0.2.5 with the respawn command. Some changes will still force a reboot but generally area changes should be more flexible.
