### ISSUE TITLE
Regenerating objects

### ISSUE THREAD

**Issue by fly-man-** [MoreOutput/RockMUD#48]
I'd like to see an ability for the server to regenerate tools / etc in the rooms

Think like a Blacksmith, being able to buy things from him and when the tools aren't available, have a timer run that restores the tools over time.

That way a user will have to come back to get tools instead of being stuck

**Comment by MoreOutput** [comment]
Respawn is coming; agree with both of your issues. Moving respawn to 0.2.5 milestone; in which it will be in its first iteration.

**Comment by MoreOutput** [comment]
Closed and covered here: https://github.com/MoreOutput/RockMUD/issues/50. This was a planned 0.3.5 feature but can be moved up since I keeps haunting me. Contributions welcome.
