### ISSUE TITLE
Placement of Health / Magic / Movement outside the box

### ISSUE THREAD

**Issue by fly-man-** [MoreOutput/RockMUD#49]
I'd love to see that the health  / magic / movement bar isn't in the text but outside the side of the screen so you can see your stats dropping down.

Now it just adds to the backlog which is already filling when you're idling in a room

**Comment by MoreOutput** [comment]
This is outside of the scope of the RM core. If a dev wanted to make gui elements they would need to leverage the 'res' property that will make its way to the client on each message -- and it would be handled there. The OOTB RM experience is to be a fairly typical mud experience. Future terminal improvements will be made but it'll be mainly typeahead and etc. It is expected/wanted that people make UX elements but its not something we want complicating the core (yet anyway).
