### ISSUE TITLE
Server crashes when creating a new player

### ISSUE THREAD

**Issue by fly-man-** [MoreOutput/RockMUD#52]
undefined:1
undefined
^
SyntaxError: Unexpected token u
    at Object.parse (native)
    at \\Development\RockMUD\src\world.js:192:19
    at fs.js:263:20
    at FSReqWrap.oncomplete (fs.js:95:15)

**Comment by fly-man-** [comment]
Already found the issue at hand, file warrior.json doesn't exist.

Pushing a pull request to fix that

**Comment by MoreOutput** [comment]
Hold off please. I have been correct these items this morning; related to the help file move. No longer using JSON but html.
