### ISSUE TITLE
Current Health going above maximum

### ISSUE THREAD

**Issue by gevrik** [MoreOutput/RockMUD#60]
In character.js manaRegen function around line 494:

`target.chp += total;`

should be:

`target.cmana += total;`

Same function around line 487:

`conMod = World.dice.roll(1, 2) - 1;`

should be :

`intMod = World.dice.roll(1, 2) - 1;`

**Comment by MoreOutput** [comment]
Blarg! Just seeing this; i have this fixed on my local and never pushed. Ill do it in a bit once work settles down.

**Comment by MoreOutput** [comment]
This bug fix is in https://github.com/MoreOutput/RockMUD/pull/61; along with some other items.
