### ISSUE TITLE
command.js Cmd.prototype.get - Bug

### ISSUE THREAD

**Issue by gevrik** [MoreOutput/RockMUD#84]
Trying to get items in the game currently results in:

TypeError: Cannot read property 'light' of undefined
    at Character.canSee (/home/gevrik/mud/rockmud/src/character.js:1076:51)
    at Cmd.get (/home/gevrik/mud/rockmud/src/commands.js:730:39)

I fixed it by adding the following to character.js Character.prototype.canSee:

```
    // check if a roomObj was passed or use the player's current room
    roomObj = (!roomObj) ?  World.getRoomObject(player.area, player.roomid) : roomObj;
```

Hope it helps.

**Comment by MoreOutput** [comment]
Sorry been on vacation; will have a look this evening or tomorrow and correct or put your fix in. Appreciate the heads up!
