### ISSUE TITLE
Leveling

### ISSUE THREAD

**Issue by wizardsambolton** [MoreOutput/RockMUD#95]

**Comment by MoreOutput** [comment]
Character.level will be called within one of the processEndOfCombat functions (processEndOfMudCombat). There it will be, on default, playerlevel * 1000.

**Comment by wizardsambolton** [comment]
Thanks!

**Comment by wizardsambolton** [comment]
Oh wait that is going to bit added or it is there already?

**Comment by MoreOutput** [comment]
leveling is not in; you can leave this open.

**Comment by wizardsambolton** [comment]
Ok cool!
