### ISSUE TITLE
Payed Transport

### ISSUE THREAD

**Issue by wizardsambolton** [MoreOutput/RockMUD#99]
Kind of like teleportation I guess but you have to pay gold for it.

**Comment by MoreOutput** [comment]
Closing this. If this is comes up naturally it will be added -- for now this seems more like a 'game' enhancement (something you'd write for your game). The way to do this would be to write an ai script that lets the mob open a portal or teleport something (switching the player.roomid and player.area to the wanted room, taking some gold, giving a message, and then firing the look command).

Teleport will be a part of base.

**Comment by wizardsambolton** [comment]
Ok thanks!
